#include "Arduino.h"

#include <atca_basic.h>
#include <atca_cfgs.h>
#include <atca_command.h>
#include <atca_compiler.h>
#include <atca_crypto_sw.h>
#include <atca_crypto_sw_sha2.h>
#include <atca_device.h>
#include <atca_devtypes.h>
#include <atca_hal.h>
#include <atca_helpers.h>
#include <atca_host.h>
#include <atca_iface.h>
#include <atca_start_config.h>
#include <atca_start_iface.h>
#include <atca_status.h>
#include <cryptoauthlib.h>
#include <hal_i2c_bitbang.h>
#include <i2c_bitbang_at88ck9000.h>
#include <sha2_routines.h>

#include <uECC.h>
#include <uECC_vli.h>
#include <types.h>

//#include <macros.h>
//#include <options.h>
//#include <sha3.h>
//#include <coins_array.h>
//#include <sha2.h>
//#include <pbkdf2.h>
//#include <hasher.h>
//#include <base32.h>
//#include <bip39.h>
//#include <messages_map.h>
//#include <bip32.h>
//#include <rfc6979.h>
//#include <crypto.h>
//#include <transaction.h>
//#include <rc4.h>
//#include <curves.h>
//#include <nem.h>
//#include <messages.pb.h>
//#include <blake2b.h>
//#include <pb_decode.h>
//#include <check_mem.h>
//#include <blake2_common.h>
//#include <bip39_english.h>
//#include <ecdsa.h>
//#include <pb.h>
//#include <script.h>
//#include <debug.h>
//#include <util.h>
//#include <signing.h>
//#include <coins.h>
//#include <messages.h>
//#include <segwit_addr.h>
//#include <gettext.h>
//#include <address.h>
//#include <base58.h>
//#include <pb_encode.h>
//#include <pb_common.h>
//#include <blake256.h>
//#include <nem_serialize.h>
//#include <bignum.h>
//#include <types.pb.h>
//#include <nist256p1.h>
//#include <rand.h>
//#include <ripemd160.h>
#include <hmac.h>
//#include <coins_count.h>
//#include <secp256k1.h>
//#include <blake2s.h>
